language: "node_js"

jobs:
  include:
    - stage: test
      node_js:
        - "7"
        - "6"
        - "5"
        - "4"
      sudo: false
      script:
        - "yarn add coveralls"
        - "commitlint-travis"
        - "yarn lint"
        - "yarn test"
        - "cat ./reports/coverage-test/lcov.info | ./node_modules/.bin/coveralls"
        - "yarn integration"
        - "yarn docs"
    - stage: compliance
      services: docker
      sudo: false
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      script:
        - "docker-compose up --abort-on-container-exit --exit-code-from bacnet-client"
    - stage: pages
      node_js: "7"
      sudo: false
      script:
        - "yarn docs"
      deploy:
        provider: pages
        local_dir: ./docs
        github_token: $GITHUB_API_KEY
        skip_cleanup: true
        on:
          tags: true
